version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - bridge_network
    command: [ "/app/server" ]

networks:
  bridge_network:
    external: false
    name: bridge_network